name: Build, test and publish to npm
on: [push, pull_request]

jobs:
  build_test:
    name: Build, test and publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.2"

      # From
      # https://github.com/actions/cache/blob/b8204782bbb5f872091ecc5eb9cb7d004e35b1fa/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          # Change suffix "v1" for cache busting:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-v1
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run unit tests
        run: yarn run test:ci
        env:
          GITHUB_TOKEN: ${{ secrets.UNIT_TEST_GITHUB_TOKEN }}
      - name: Run linters
        run: yarn run lint
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
      - name: Publish to npm
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 15.13.16
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
